version: "3"
services:
    ccli:
        image: "ccli:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: ccli
        stdin_open: true
        tty: true
        working_dir: '/ccli-dev'
        volumes:
            - ".:/ccli-dev"
